/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * daireEkle.java
 *
 * Created on 07.Haz.2009, 15:25:29
 */
package Arayuz;

import islemler.aidatAl;
import islemler.aidatBilgisiAl;
import islemler.aidatBilgisiKaydet;
import islemler.aidatKaydet;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import pojo.Aidatbilgileri;
import pojo.Aidatlar;

/**
 *
 * @author racih
 */
public class daireEkle extends javax.swing.JDialog {

    private EntityManager em;
    private EntityManagerFactory _emf;
    private aidatKaydet daire;
    private aidatAl aa;
    private aidatBilgisiKaydet abk;
    private int blok;
    private aidatBilgisiAl aba;

    /** Creates new form daireEkle */
    public daireEkle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        int width = getWidth();
        int height = getHeight();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width - width) / 2;
        int y = (screen.height - height) / 2;
        setBounds(x, y, width, height);
    }

    public void Baglanti(EntityManagerFactory emf, int blokid) {
        blok = new Integer(blokid);
        _emf = emf;
        em = emf.createEntityManager();
        aa = new aidatAl(emf);
        abk = new aidatBilgisiKaydet(emf);
        daire = new aidatKaydet(emf);
        lbl_blok.setText(blok());
        aba = new aidatBilgisiAl(emf);
        onYukleme();
    }

    private void onYukleme() {
        cmb_tarih.removeAllItems();
        Query s = em.createQuery("SELECT y.yil FROM Yillar y");
        List l = s.getResultList();
        for (int i = 0; i < l.size(); i++) {
            cmb_tarih.addItem(l.get(i).toString());
        }
        listeyeEkle();
    }

    private String blok() {
        String b = null;
        switch (blok) {
            case 0:
                b = "59";
                break;
            case 1:
                b = "61";
                break;
            case 2:
                b = "63";
                break;
            case 3:
                b = "25";
        }
        return b;
    }

    private void kaydet() {
        try {

            if (txt_daire.getText().isEmpty() != false) {
                JOptionPane.showMessageDialog(this, "Veri Girin !", "Hata", 1);
                return;
            }

            String tarih = cmb_tarih.getSelectedItem().toString();
            int id = aa.siraBul();
            Aidatlar a = new Aidatlar(id, tarih, blok() + "/" + txt_daire.getText());
            Aidatbilgileri ab = new Aidatbilgileri(id, tarih, blok() + "/" + txt_daire.getText());
            abk.aidatBilgisiOlustur(ab);
            daire.daireOlustur(a);
            listeyeEkle();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Sil() {
        try {
            if (list_daireler.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(this, "Lütfen Daire Seçin !", "Hata", 1);
                return;
            }
            daire.daireSil(lbl_blok.getText()+"/"+list_daireler.getSelectedValue().toString(), cmb_tarih.getSelectedItem().toString());
            listeyeEkle();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void listeyeEkle() {
        DefaultListModel l = new DefaultListModel();
        String tarih = cmb_tarih.getSelectedItem().toString();
        for (int i = 0; i < aba.AlTarih().size(); i++) {
            String dbTarih = aba.AlTarih().get(i).toString();
            if (tarih.equals(dbTarih) != false) {
                String Blokx = aba.AlDaire().get(i).toString();
                String dbBlok = Blokx.substring(Blokx.indexOf(""), Blokx.lastIndexOf("/"));
                if (blok().equals(dbBlok) != false) {
                    String dairex = aba.AlDaire().get(i).toString();
                    String dbDaire = dairex.substring(dairex.indexOf("/") + 1, dairex.lastIndexOf(""));
                    l.addElement(dbDaire);
                }
            }
        }
        list_daireler.setModel(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_blok = new javax.swing.JLabel();
        lbl_blok1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_daireler = new javax.swing.JList();
        txt_daire = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_ekle = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_kisiEkle = new javax.swing.JButton();
        cmb_tarih = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aidat Takip Daire Ekle");

        lbl_blok.setText("-");

        lbl_blok1.setText("Bloğuna daire Ekle");

        list_daireler.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_daireler);

        jLabel1.setText("Daire :");

        btn_ekle.setText("Ekle");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        btn_sil.setText("Sil");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_kisiEkle.setText("Kişi Ekle");
        btn_kisiEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kisiEkleActionPerformed(evt);
            }
        });

        cmb_tarih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Yıllar :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_blok, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_blok1)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_daire, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btn_kisiEkle)))
                        .addGap(61, 61, 61)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_blok)
                    .addComponent(lbl_blok1)
                    .addComponent(cmb_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_daire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ekle)
                            .addComponent(btn_sil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_kisiEkle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        // TODO add your handling code here:
        kaydet();
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        // TODO add your handling code here:
        Sil();
    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_kisiEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kisiEkleActionPerformed
        // TODO add your handling code here:
        if (list_daireler.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Daire Seçin !", "Hata", 1);
            return;
        }
        String dairex = list_daireler.getSelectedValue().toString();
        kisiEkle ks = new kisiEkle(null, true);
        ks.Baglanti(_emf, dairex);
        ks.setVisible(true);
    }//GEN-LAST:event_btn_kisiEkleActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_kisiEkle;
    private javax.swing.JButton btn_sil;
    private javax.swing.JComboBox cmb_tarih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_blok;
    private javax.swing.JLabel lbl_blok1;
    private javax.swing.JList list_daireler;
    private javax.swing.JTextField txt_daire;
    // End of variables declaration//GEN-END:variables
}
