/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * sifreDegistir.java
 *
 * Created on 07.Haz.2009, 17:09:34
 */

package Arayuz;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import pojo.Uye;

/**
 *
 * @author racih
 */
public class sifreDegistir extends javax.swing.JDialog {
    private EntityManager em;

    /** Creates new form sifreDegistir */
    public sifreDegistir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        int width = getWidth();
        int height = getHeight();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width - width) / 2;
        int y = (screen.height - height) / 2;
        setBounds(x, y, width, height);
    }

     public void Baglanti(EntityManagerFactory emf) {
        em = emf.createEntityManager();
    }

      private void Degistir() {
        try {
            if (txt_kullaniciAdi.getText().isEmpty() != false) {
            JOptionPane.showMessageDialog(this, "Kullanıcı Adı Girin !", "Hata !", 1);
            return;
        }
        if (txt_eskiSifre.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Eski Şifreyi Girin !", "Hata !", 1);
            return;
        }
        if (txt_yeniSifre.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Yeni Şifreyi Girin !", "Hata !", 1);
            return;
        }
        if (txt_sifreTekrar.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Yeni Şifreyi Girin !", "Hata !", 1);
            return;
        }
        String yeniIsim = txt_kullaniciAdi.getText();
        char[] eskiSifreX = txt_eskiSifre.getPassword();
        char[] yeniSifreX = txt_yeniSifre.getPassword();
        char[] sifreTekrarX = txt_sifreTekrar.getPassword();
        String eskiSifre = new String(eskiSifreX);
        String yeniSifre = new String(yeniSifreX);
        String sifreTekrar = new String(sifreTekrarX);
        String dbEskiSifre = null;
        Uye kisi = em.find(Uye.class, 1);
        if (kisi != null) {
            dbEskiSifre = kisi.getSifre();
        }
        if (dbEskiSifre.equals(eskiSifre) != false) {
            if (yeniSifre.equals(sifreTekrar) != false) {
                kisi.setKullanici(yeniIsim);
                kisi.setSifre(yeniSifre);
                uyeDegistir(kisi);
                JOptionPane.showMessageDialog(this, "İşlem Başarılı","Bilgi",1);
                dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Yeni şifre tekrarı uyuşmuyor !","Hata !", 2);
            }
        }else{
                JOptionPane.showMessageDialog(this, "Eski Şifre Yanlış !","Hata !", 2);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private  void uyeDegistir(Uye e) {
        em.getTransaction().begin();
        em.merge(e);
        em.getTransaction().commit();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kullaniciAdi = new javax.swing.JTextField();
        txt_eskiSifre = new javax.swing.JPasswordField();
        txt_yeniSifre = new javax.swing.JPasswordField();
        txt_sifreTekrar = new javax.swing.JPasswordField();
        btn_kaydet = new javax.swing.JButton();
        btn_vazgec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aidat Takip Şifre Değiştir");

        jLabel1.setText("Yeni Kullanıcı Adı :");

        jLabel2.setText("Eski Şifre :");

        jLabel3.setText("Yeni Şifre :");

        jLabel4.setText("Şifre Tekrar :");

        txt_sifreTekrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sifreTekrarKeyPressed(evt);
            }
        });

        btn_kaydet.setText("Tamam");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        btn_vazgec.setText("Vazgeç");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_kaydet)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sifreTekrar, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_eskiSifre, 0, 0, Short.MAX_VALUE)
                                .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_yeniSifre, 0, 0, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btn_vazgec)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_eskiSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_yeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_sifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kaydet)
                    .addComponent(btn_vazgec))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed
        // TODO add your handling code here:
        Degistir();
    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void txt_sifreTekrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sifreTekrarKeyPressed
        // TODO add your handling code here:
        int Tus = evt.getKeyCode();
        if (Tus == KeyEvent.VK_ENTER) {
            Degistir();

        }
        if (Tus == KeyEvent.VK_ESCAPE) {
            dispose();
        }
    }//GEN-LAST:event_txt_sifreTekrarKeyPressed

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JButton btn_vazgec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txt_eskiSifre;
    private javax.swing.JTextField txt_kullaniciAdi;
    private javax.swing.JPasswordField txt_sifreTekrar;
    private javax.swing.JPasswordField txt_yeniSifre;
    // End of variables declaration//GEN-END:variables

}
